import './globals.css'
import { Inter } from 'next/font/google'
import { ChakraProvider, ColorModeScript } from '@chakra-ui/react'
import Providers from './Providers'
import { theme } from './theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
          {/* <ColorModeScript theme={theme.config.initialColorMode} /> */}
          <Providers>
            {children}
          </Providers>
          </body>
      </html>
  )
}
